MOD-651 Backup in prod env (#568)
<!-- This is an auto-generated comment: release notes by OSS CodeRabbit
-->
### Summary by CodeRabbit

- New Feature: Added a step to generate a deployment tag and store it in
the environment variables and `.env` file, improving traceability of
deployments.
- Refactor: Updated GitHub Actions workflows to trigger only on pull
requests targeting the "main" branch, enhancing workflow efficiency.
- New Feature: Introduced a shell script for backup operations,
replacing the direct command execution. This enhances maintainability
and readability of the backup process.
- Chore: Modified the backup step in `deploy_qa.yml` to set the
"ENVIRONMENT" variable to "qa", ensuring correct environment context
during backups.
- Refactor: Removed redundant deployment tag generation from the "Add
GitHub Tag" step in `create_proposal.yml`.
- New Feature: Added a backup step before deployment, which executes a
backup script and sends a notification to a Slack channel, increasing
data safety and visibility of backup operations.
<!-- end of auto-generated comment: release notes by OSS CodeRabbit -->

diff --git a/.github/workflows/create_proposal.yml b/.github/workflows/create_proposal.yml
--- a/.github/workflows/create_proposal.yml
+++ b/.github/workflows/create_proposal.yml
@@ -45,6 +45,14 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Generate DEPLOYMENT_TAG
+        id: generate-tag
+        run: |
+          DEPLOYMENT_TAG="PROD-$(date +'%Y-%m-%d-%H.%M')"
+          echo "DEPLOYMENT_TAG=${DEPLOYMENT_TAG}" >> "$GITHUB_ENV"
+          echo "DEPLOYMENT_TAG=${DEPLOYMENT_TAG}" >> .env
+          cat .env
+
       - name: Set inputs as env variables
         run: |
           echo "TITLE=${{ github.event.inputs.TITLE }}" >> $GITHUB_ENV
@@ -124,6 +132,19 @@ jobs:
           CANISTER: ${{ github.event.inputs.CANISTER }}
           ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT }}
 
+      - name: Backup - before deployment
+        run: |
+          if ! ./scripts/deployment/gh_backup.sh; then
+            echo "Backup failed"
+            exit 1
+          fi
+
+          PAYLOAD="{\"text\":\"Backup [$BACKUP_ID_1 - $BACKUP_FIELDNAME_1]\"}"
+          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $PROPOSAL_NOTIFICATION_SLACK_HOOK
+        env:
+          ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT }}
+          PROPOSAL_NOTIFICATION_SLACK_HOOK: ${{ secrets.PROPOSAL_NOTIFICATION_SLACK_HOOK }}
+
       - name: Execute canister upgrade proposal script
         if: success()
         run: |
@@ -140,7 +161,6 @@ jobs:
       - name: Add GitHub Tag
         if: success()
         run: |
-          DEPLOYMENT_TAG="PROD-$(date +'%Y-%m-%d-%H.%M')"
           git tag $DEPLOYMENT_TAG
           git push origin $DEPLOYMENT_TAG
 
